"""initial infrastructure lifecycle schema

Revision ID: 3f012f421ca0
Revises:
Create Date: 2026-09-11 23:21:05.983384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f012f421ca0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('product_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=40), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('purl', sa.String(length=500), nullable=True),
    sa.Column('cpe', sa.String(length=500), nullable=True),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('security_end_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_source_url', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type', 'vendor', 'name', 'version', name='uq_product_release_identity')
    )
    op.create_index(op.f('ix_product_releases_cpe'), 'product_releases', ['cpe'], unique=True)
    op.create_index(op.f('ix_product_releases_eol_date'), 'product_releases', ['eol_date'], unique=False)
    op.create_index(op.f('ix_product_releases_name'), 'product_releases', ['name'], unique=False)
    op.create_index(op.f('ix_product_releases_product_type'), 'product_releases', ['product_type'], unique=False)
    op.create_index(op.f('ix_product_releases_purl'), 'product_releases', ['purl'], unique=True)
    op.create_index(op.f('ix_product_releases_security_end_date'), 'product_releases', ['security_end_date'], unique=False)
    op.create_index(op.f('ix_product_releases_support_end_date'), 'product_releases', ['support_end_date'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('annual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('service_level', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_no'), 'contracts', ['contract_no'], unique=True)
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_end_date'), 'contracts', ['end_date'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'site_code', name='uq_customer_site_code')
    )
    op.create_index(op.f('ix_sites_customer_id'), 'sites', ['customer_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('model_release_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('site', sa.String(length=160), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(length=80), nullable=True),
    sa.Column('introduced_on', sa.Date(), nullable=True),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_source_url', sa.Text(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_release_id'], ['product_releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_index(op.f('ix_assets_model_release_id'), 'assets', ['model_release_id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_index(op.f('ix_assets_support_end_date'), 'assets', ['support_end_date'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_stage', sa.String(length=20), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_asset_id'), 'collection_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_table('contract_assets',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', 'asset_id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('software_product_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=40), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_product_id'], ['product_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'software_product_id', name='uq_deployment')
    )
    op.create_index(op.f('ix_deployments_asset_id'), 'deployments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_deployments_software_product_id'), 'deployments', ['software_product_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_job_id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('max_disk_percent', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('health_level', sa.String(length=20), nullable=False),
    sa.Column('disk_details', sa.JSON(), nullable=False),
    sa.Column('process_details', sa.JSON(), nullable=False),
    sa.Column('raw_metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_results_collection_job_id'), 'check_results', ['collection_job_id'], unique=True)
    op.create_table('sbom_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('bom_format', sa.String(length=40), nullable=False),
    sa.Column('spec_version', sa.String(length=20), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('software_product_id', sa.Integer(), nullable=True),
    sa.Column('collection_job_id', sa.Integer(), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('dependency_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_details', sa.JSON(), nullable=False),
    sa.Column('raw_document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['software_product_id'], ['product_releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', 'document_version', name='uq_sbom_version')
    )
    op.create_index(op.f('ix_sbom_documents_asset_id'), 'sbom_documents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sbom_documents_collection_job_id'), 'sbom_documents', ['collection_job_id'], unique=False)
    op.create_index(op.f('ix_sbom_documents_serial_number'), 'sbom_documents', ['serial_number'], unique=False)
    op.create_index(op.f('ix_sbom_documents_software_product_id'), 'sbom_documents', ['software_product_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbom_id', sa.Integer(), nullable=False),
    sa.Column('product_release_id', sa.Integer(), nullable=True),
    sa.Column('bom_ref', sa.String(length=600), nullable=False),
    sa.Column('component_type', sa.String(length=40), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=160), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('purl', sa.String(length=700), nullable=True),
    sa.Column('cpe', sa.String(length=700), nullable=True),
    sa.Column('licenses', sa.JSON(), nullable=False),
    sa.Column('hashes', sa.JSON(), nullable=False),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_release_id'], ['product_releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sbom_id'], ['sbom_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sbom_id', 'bom_ref', name='uq_component_bom_ref')
    )
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_product_release_id'), 'components', ['product_release_id'], unique=False)
    op.create_index(op.f('ix_components_purl'), 'components', ['purl'], unique=False)
    op.create_index(op.f('ix_components_sbom_id'), 'components', ['sbom_id'], unique=False)
    op.create_index(op.f('ix_components_support_end_date'), 'components', ['support_end_date'], unique=False)
    op.create_index(op.f('ix_components_version'), 'components', ['version'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbom_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=600), nullable=False),
    sa.Column('target_ref', sa.String(length=600), nullable=False),
    sa.ForeignKeyConstraint(['sbom_id'], ['sbom_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sbom_id', 'source_ref', 'target_ref', name='uq_dependency_edge')
    )
    op.create_index(op.f('ix_dependency_edges_sbom_id'), 'dependency_edges', ['sbom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependency_edges_sbom_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_components_version'), table_name='components')
    op.drop_index(op.f('ix_components_support_end_date'), table_name='components')
    op.drop_index(op.f('ix_components_sbom_id'), table_name='components')
    op.drop_index(op.f('ix_components_purl'), table_name='components')
    op.drop_index(op.f('ix_components_product_release_id'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_sbom_documents_software_product_id'), table_name='sbom_documents')
    op.drop_index(op.f('ix_sbom_documents_serial_number'), table_name='sbom_documents')
    op.drop_index(op.f('ix_sbom_documents_collection_job_id'), table_name='sbom_documents')
    op.drop_index(op.f('ix_sbom_documents_asset_id'), table_name='sbom_documents')
    op.drop_table('sbom_documents')
    op.drop_index(op.f('ix_check_results_collection_job_id'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_deployments_software_product_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_asset_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('contract_assets')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_asset_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_assets_support_end_date'), table_name='assets')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_model_release_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sites_customer_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_contracts_end_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_no'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_product_releases_support_end_date'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_security_end_date'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_purl'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_product_type'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_name'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_eol_date'), table_name='product_releases')
    op.drop_index(op.f('ix_product_releases_cpe'), table_name='product_releases')
    op.drop_table('product_releases')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
